<?php
$labels['acc_autoreply'] = 'Autoreply';
$labels['autoreplymessage'] = 'Message';
$labels['autoreplyenabled'] = 'Enabled';
$labels['and'] = 'and';
$labels['autoreplystarton'] = 'Start on';
$labels['autoreplyendby'] = 'End by';
$messages['textempty'] = 'Please enter a message';
$messages['startdate_notfuture'] = 'Start date cannot be in the past';
$messages['autoresponder_end_date_isgreater'] = 'End date must be set and be later than start date.';
