<?php
$labels['acc_autoreply'] = 'Autobeantwoorden';
$labels['autoreplymessage'] = 'Berichtinhoud';
$labels['autoreplyenabled'] = 'Ingeschakeld';
$labels['and'] = 'en';
$labels['autoreplystarton'] = 'Begint op';
$labels['autoreplyendby'] = 'Eindigt op';
$messages['textempty'] = 'Vul a.u.b. een bericht in.';
$messages['startdate_notfuture'] = 'Startdatum kan niet in het verleden liggen';
$messages['autoresponder_end_date_isgreater'] = 'Einddatum moet worden ingesteld en moet later zijn dan de startdatum';