<?php
$labels['acc_autoreply'] = 'Автовідповідач';
$labels['autoreplymessage'] = 'Повідомлення';
$labels['autoreplyenabled'] = 'увімкнути';
$labels['and'] = 'і';
$labels['autoreplystarton'] = 'початок';
$labels['autoreplyendby'] = 'закінчення';
$messages['textempty'] = 'Будь ласка, введіть повідомлення';
$messages['startdate_notfuture'] = 'Дата початку не може бути в минулому';
$messages['autoresponder_end_date_isgreater'] = 'Дата закінчення обов\'язкова і не може бути раніше дати початку';